# Generated by Django 3.0.3 on 2020-08-19 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='開始時間'),
        ),
    ]
