# Generated by Django 3.0.3 on 2020-09-01 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='締切日'),
        ),
    ]
