# Generated by Django 3.0.3 on 2020-09-07 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_todo_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='開始時間'),
        ),
    ]
