# Generated by Django 3.0.3 on 2020-10-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_custom_repeat_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='repeat_flag',
            field=models.CharField(max_length=7),
        ),
    ]
