# Generated by Django 3.0.3 on 2020-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20201010_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
    ]
